Implement release channels in the launcher.
chunky-dev/chunky pull request #1080
Opened 2021-12-04 10:01 UTC by ThatRedox

Replace the download snapshots checkmark box with a channel selection dropdown. Allow updating if the version is not already downloaded, changed from only if it is a chronologically newer version. Bump launcher version to 1.13.0. Add a launcher settings revision field for possible future use.
![image](https://user-images.githubusercontent.com/42661490/144705143-4dcead83-6e96-461d-b2b2-bc54a3649a18.png)
![image](https://user-images.githubusercontent.com/42661490/144705153-b8bd966d-3b59-4d1f-bc27-3242f0aa42a1.png)

2021-12-04 18:37 UTC, ThatRedox commented
Implement launcher version checking on startup.
![image](https://user-images.githubusercontent.com/42661490/144720818-1cfc1a71-6742-4cd9-b830-2da62e026344.png)

2021-12-04 18:39 UTC, ThatRedox commented
New features require the update site to have a `launcher.json` such as:
```json
{
  "name": "1.13.0",
  "timestamp": "2021-12-04T06:48:21Z",
  "notes": "Thanks to all the ...",
  "path": "ChunkyLauncher.jar",
  "channels": [
    {
      "name": "Stable",
      "path": "latest.json",
      "notes": "Latest stable version of Chunky."
    },
    {
      "name": "Beta",
      "path": "snapshot-stable.json",
      "notes": "Latest beta version of Chunky. Snapshots of next stable patch or release candidates."
    },
    {
      "name": "Snapshot",
      "path": "snapshot.json",
      "notes": "Latest nightly snapshot of Chunky."
    }
  ]
}
```
Old update sites are still compatible.

2021-12-26 15:50 UTC, leMaik requested changes

2021-12-26 15:50 UTC, leMaik commented on launcher/src/se/llbit/chunky/launcher/LauncherInfoChecker.java
> +        } catch (Throwable e) {
If we get a `RuntimeException` or just any `Throwable` here, something is seriously wrong… we shouldn't handle that.

```suggestion
        } catch (Exception e) {
```

2021-12-26 15:50 UTC, leMaik commented on launcher/src/se/llbit/chunky/launcher/ui/ChunkyLauncherController.java
> +              launcherError("Failed to Update", error);
```suggestion
              launcherError("Failed to update the launcher", error);
```

2021-12-26 15:50 UTC, leMaik commented on lib/src/se/llbit/chunky/launcher/LauncherSettings.java
> +    releaseChannels.add(SNAPSHOT_RELEASE_CHANNEL);
Would it be enough to only add these if we can't find a `launcher.json`?

2021-12-26 15:50 UTC, leMaik commented on lib/src/se/llbit/chunky/launcher/LauncherSettings.java
> +    releaseChannelsObject.set("selectedChannel", new JsonNumber(selectedChannelValue));
Instead of storing the index, why not assign IDs to the channels?

2021-12-27 22:28 UTC, merged