Add a control to lock the camera angle.
chunky-dev/chunky pull request #1469
Opened 2022-10-12 20:21 UTC by Peregrine05

Fixes #1396.

The control is the third in the render preview right-click menu. Since Chunky already does not change the camera angle if the secondary mouse button is used to drag the preview, right clicking on the preview to access the control should not be an issue.

**New:**
![image](https://user-images.githubusercontent.com/92183530/195439752-cd7abf1f-a2d7-4823-a09e-16a4c6c7ac91.png)

2022-10-12 20:36 UTC, jackjt8 commented
This PR works as intended.

Though I would also like it to be a more general `Lock camera` button as currently you can also change FoV via the scroll wheel. Additional functionality would be to also ignore keyboard commands... but that's probably too far out of scope for the issue and this PR.

2022-10-13 00:34 UTC, ThatRedox commented
I agree with Jack, I think more camera locking controls would be useful. Perhaps put them in the `Camera` tab and associate them with different cameras?

2022-10-13 00:34 UTC, ThatRedox commented on chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
> +      if (e.isSecondaryButtonDown() | lockCameraAngle.isSelected()) {
```suggestion
      if (e.isSecondaryButtonDown() || lockCameraAngle.isSelected()) {
```

2022-10-13 00:36 UTC, ThatRedox requested changes

2022-10-13 00:36 UTC, ThatRedox commented on chunky/src/java/se/llbit/chunky/ui/RenderCanvasFx.java
> +      if (e.isSecondaryButtonDown() | lockCameraAngle.isSelected()) {
```suggestion
      if (e.isSecondaryButtonDown() || lockCameraAngle.isSelected()) {
```

2022-10-20 21:54 UTC, ThatRedox approved these changes
Looks good! I would see if we could get the lock UI from the canvas size lock but it's not super important.

2022-11-25 22:33 UTC, merged