Fix issue where sun would contribute to reflections despite `Draw Sun` being disabled.
chunky-dev/chunky pull request #1576
Opened 2023-04-14 03:57 UTC by ThatRedox

If `Draw sun` and `Sun Sampling Strategy are disabled, the sun still contributes to reflections:
![image](https://user-images.githubusercontent.com/42661490/231937606-5ce434cd-ee59-4b63-8599-826dac3f721a.png)
(500 exposure).

This PR adds the `drawSun` check to `Sun.diffuseIntersect` which was causing this issue.

2023-04-14 07:12 UTC, leMaik approved these changes

2023-04-14 10:23 UTC, Peregrine05 requested changes
This PR makes non-sampled sunlight again depend on the state of the `Draw sun` control (The issue was #1317, and was fixed by #1474). The `Draw sun` control should have no effect over the sunlight that the scene receives. If a user wishes to disable sunlight, then the user should set `Sun Sampling Strategy` to `NON_LUMINOUS`.

Maybe use instead to retain previous behavior:
```java
  public boolean intersect(Ray ray) {
    return doIntersect(ray, apparentTextureBrightness, false);
  }

  /**
   * Used with <code>SSS: OFF</code> and <code>SSS: HIGH_QUALITY</code>.
   */
  public boolean intersectDiffuse(Ray ray) {
    return doIntersect(ray, color, true);
  }

  private boolean doIntersect(Ray ray, Vector3 color, boolean isDiffuse) {
    if ((!isDiffuse && !drawTexture) || ray.d.dot(sw) < .5) {
      return false;
    }

    double width = radius * 4;
    double width2 = width * 2;
    double a;
    a = Math.PI / 2 - FastMath.acos(ray.d.dot(su)) + width;
    if (a >= 0 && a < width2) {
      double b = Math.PI / 2 - FastMath.acos(ray.d.dot(sv)) + width;
      if (b >= 0 && b < width2) {
        texture.getColor(a / width2, b / width2, ray.color);
        ray.color.x *= color.x * 10;
        ray.color.y *= color.y * 10;
        ray.color.z *= color.z * 10;
        return true;
      }
    }

    return false;
  }
```

2023-04-14 10:34 UTC, Peregrine05 requested changes

2023-04-14 10:34 UTC, Peregrine05 commented on chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java
> +    return doIntersect(ray, apparentTextureBrightness);
```suggestion
    return doIntersect(ray, apparentTextureBrightness, false);
```

2023-04-14 10:34 UTC, Peregrine05 commented on chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java
> +    return doIntersect(ray, color);
```suggestion
    return doIntersect(ray, color, true);
```

2023-04-14 10:34 UTC, Peregrine05 commented on chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java
> +  private boolean doIntersect(Ray ray, Vector3 color) {
```suggestion
  private boolean doIntersect(Ray ray, Vector3 color, boolean isDiffuse) {
```

2023-04-14 10:34 UTC, Peregrine05 commented on chunky/src/java/se/llbit/chunky/renderer/scene/Sun.java
> +    if (!drawTexture || ray.d.dot(sw) < .5) {
```suggestion
    if ((!isDiffuse && !drawTexture) || ray.d.dot(sw) < .5) {
```

2023-04-14 16:26 UTC, ThatRedox commented
> This is not a bug. Sunlight is meant to be disabled not with the `Draw sun` control, but rather with the `Sun Sampling Strategy` control set to `NON_LUMINOUS`.

Calling it `Sun Sampling Strategy` is confusing then. And one would expect `OFF` to be able to turn off the sun, not `NON_LUMINOUS`.

2023-04-14 16:51 UTC, Peregrine05 commented
I suggest that we put a hint in the `Lighting` tab then, as is done in other parts of the GUI.

> The 'Draw sun' control only changes the visibility of the texture of the sun. Set 'Sun Sampling Strategy' to 'NON_LUMINOUS' to disable sunlight.

2023-04-16 22:41 UTC, ThatRedox commented
Replaced by #1577

2023-04-16 22:41 UTC, closed without merging