Implement plugin dependencies, loaded in dependency first order
chunky-dev/chunky pull request #1701
Opened 2024-03-06 11:06 UTC by NotStirred

This PR doesn't implement a plugin loader API but that is now ready for another PR.

Outstanding things:
- Added one dependency `org.apache.maven:maven-artifact:3.9.6` (Apache 2)
- Errors and warnings reported in plugin loading are not presented to the UI as plugins are loaded before the receiver is set.

2024-09-23 21:11 UTC, leMaik commented on chunky/src/java/se/llbit/chunky/main/Chunky.java
> +      .flatMap(o -> o.map(Stream::of).orElseGet(Stream::empty)) // replace with Optional::stream in java9+
We're on Java 17 now

2024-09-23 21:14 UTC, leMaik commented on chunky/src/java/se/llbit/chunky/plugin/loader/JarPluginLoader.java
> +      Log.error("Plugin main class has wrong type", e);
```suggestion
      Log.error("Plugin main class has wrong type (must implement se.llbit.chunky.Plugin)", e);
```

2024-09-23 21:15 UTC, leMaik commented on chunky/src/java/se/llbit/chunky/plugin/loader/JarPluginLoader.java
> +   * This method is {@link PluginApi} to allow plugins to override only classloading functionality of the default plugin loader.
Is there an actual use-case for overriding the plugin loader?

2024-09-23 21:15 UTC, leMaik requested changes
Looks good, just unsure whether we need the plugin loader to be pluggable.

2024-09-23 22:42 UTC, NotStirred commented
Yes that is one of the main goals for this PR, do you remember the discussion about having a plugin that would transform 2.4.x plugins to support 2.5.x etc.? That's the main reason

2024-09-23 23:11 UTC, leMaik commented
Ah, indeed I do remember this. Allright. :+1:

2024-09-24 09:40 UTC, leMaik approved these changes

2024-09-24 20:20 UTC, leMaik commented
I added the new dependency to the readme etc. and replaced semver4j with maven-artifact. What do you think about the last two commits, @NotStirred?

2024-09-25 14:21 UTC, NotStirred commented
Chunky is not and never has been semver, and plugins are almost definitely not either

2024-09-25 14:32 UTC, NotStirred commented
new commits look good, thanks 👍

2024-09-29 20:48 UTC, merged