Reworked Error and Warning boxes.
chunky-dev/chunky pull request #782
Opened 2021-01-15 02:18 UTC by StanleyMines

This should solve https://github.com/chunky-dev/chunky/issues/739.

Changes:
* Error box now puts itself ontop of the chunky window. (if possible, won't let it be put behind any other window).
* Group Warnings together and use ChunkyErrorDialog object.
* Having warnings up no longer prevents the main UI from being interacted with (side effect of using Stage instead of Alert).
* Pressing escape to dismiss ChunkyErrorDialog only triggers on KeyReleased, so you wont accidentally dismiss all errors and warnings when meaning to only dismiss one of the two.
* Log.Level enum now holds its name in a final string.
* Renamed ErrorDialog.fxml to DialogError.fxml and copied most of that into DialogWarning.fxml (Feel free to rename back).
* Other little bits of code cleanup.

2021-01-15 10:11 UTC, jackjt8 reviewed
These changes function as expected. And makes dealing with multiple warnings much easier.

Just need to wait for an actual code review now..

2021-01-16 22:54 UTC, leMaik approved these changes
Awesome! :tada: 

Two minor things that I'll just change myself: `ErrorDialog` and `WarningDialog` are pretty good names. I'll also move the level name out of the `Level` enum (that's UI-related; maybe we want to allow translating them or something eventually).

2021-01-16 23:01 UTC, NotStirred requested changes
Misc style changes

2021-01-16 23:01 UTC, NotStirred commented on chunky/src/java/se/llbit/chunky/ui/UILogReceiver.java
> +          catch (IOException e) { throw new Error("Failed to create warning dialog", e); }
```suggestion
        if (warningDialog == null) {
          try { 
            warningDialog = new ChunkyErrorDialog(level); 
          } catch (IOException e) { 
            throw new Error("Failed to create warning dialog", e); 
          }
        }
```

2021-01-16 23:01 UTC, NotStirred commented on chunky/src/java/se/llbit/chunky/ui/UILogReceiver.java
> +          catch (IOException e) { throw new Error("Failed to create error dialog", e); }
```suggestion
      default:
        if (errorDialog == null) {
          try { 
            errorDialog = new ChunkyErrorDialog(level); 
          } catch (IOException e) {
            throw new Error("Failed to create error dialog", e); 
          }
        }
```

2021-01-17 14:53 UTC, leMaik commented on chunky/src/java/se/llbit/chunky/ui/UILogReceiver.java
> +            warningDialog = new ChunkyErrorDialog(level);
:bug: This will result in the warning dialog being called "Info Summary" if the level of the first message is INFO.

2021-01-17 14:58 UTC, merged