Postprocessing plugin api
chunky-dev/chunky pull request #949
Opened 2021-05-15 21:20 UTC by aTom3333

This changes how post processing is done to create an plug-in api to add new post processing filters. The implementation is very similar to how export format are handled.
Close #406

2021-05-15 21:48 UTC, leMaik commented on chunky/src/java/se/llbit/chunky/renderer/postprecessing/ACESFilmicFilter.java
> +    // https://knarkowicz.wordpress.com/2016/01/06/aces-filmic-tone-mapping-curve/
Maybe `@link` this in the class javadoc? That way the source will show up in the javadocs.

2021-05-15 22:05 UTC, leMaik requested changes
Nice! :clap: Just a few small suggestions

2021-05-15 22:05 UTC, leMaik commented on chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java
> +            .orElse(PostProcessingFilters.getDefault());
Maybe add a warning, something like this:

```suggestion
            .orElse(() -> {
              if (json.get("postprocess").stringValue(null) != null) {
                Log.warn("The post processing filter " + json + " is unknown. Maybe you're missing a plugin that was used to create this scene?");
              }
              return PostProcessingFilters.getDefault();
            });
```

2021-05-15 22:05 UTC, leMaik commented on chunky/src/java/se/llbit/chunky/renderer/postprecessing/PostProcessingFilters.java
> +  }
Please `@Deprecated` and `// TODO` this. I know it's required for now but at some point we should only use IDs to identify and get dynamically registered things. This requires a new Combobox that supports IDs _and_ display names so is for another PR.

2021-05-15 22:28 UTC, aTom3333 commented on chunky/src/java/se/llbit/chunky/renderer/postprecessing/Tonemap1Filter.java
> +    // http://filmicworlds.com/blog/filmic-tonemapping-operators/
Isn't the uncharted the same as Hable?

2021-05-15 22:29 UTC, leMaik commented on chunky/src/java/se/llbit/chunky/renderer/postprecessing/Tonemap1Filter.java
> +    // http://filmicworlds.com/blog/filmic-tonemapping-operators/
Oh… well it's been a few years since I added hable :sweat_smile:

2021-05-15 22:29 UTC, aTom3333 commented on chunky/src/java/se/llbit/chunky/renderer/postprecessing/Tonemap1Filter.java
> +    // http://filmicworlds.com/blog/filmic-tonemapping-operators/
Yeah ok, Hable is the name of the author of this post, this is indeed the same

2021-05-16 00:54 UTC, aTom3333 commented
Oops the preview is broken, will fix tomorrow

2021-05-16 10:59 UTC, aTom3333 commented on chunky/src/java/se/llbit/chunky/renderer/postprecessing/PostProcessingFilter.java
> +  void processPixel(int width, int height, double[] input, int x, int y, double exposure, double[] output);
Done by splitting into interfaces, Tiff export will fail if it is not possible to do per pixel post processing but everything else will work

2021-05-16 15:55 UTC, leMaik approved these changes
Is the preview fixed?

2021-05-16 15:55 UTC, leMaik commented on chunky/src/java/se/llbit/chunky/renderer/postprocessing/PixelPostProcessingFilter.java
> +public interface PixelPostProcessingFilter extends PostProcessingFilter {
```suggestion
@PluginApi
public interface PixelPostProcessingFilter extends PostProcessingFilter {
```

2021-05-16 15:56 UTC, aTom3333 commented
Yes it is, the pixel copying was the issue

2021-05-16 16:10 UTC, leMaik approved these changes

2021-05-16 16:11 UTC, merged